"""
NEXAH Navigation Demo

This script demonstrates how the NEXAH framework can navigate
state graphs generated by external system adapters.

Pipeline:

External System
      ↓
Adapter
      ↓
State Graph
      ↓
Navigation Policy
      ↓
Path through the system

Goal:
Avoid risk states while navigating the system graph.
"""

from APPLICATIONS.adapters.examples.lorenz_adapter import LorenzAdapter
from APPLICATIONS.adapters.examples.kuramoto_adapter import KuramotoAdapter
from APPLICATIONS.adapters.examples.powergrid_adapter import PowerGridAdapter
from APPLICATIONS.adapters.examples.supply_chain_adapter import SupplyChainAdapter
from APPLICATIONS.adapters.examples.traffic_adapter import TrafficAdapter


# -----------------------------------------------------------
# Simple Navigation Policy
# -----------------------------------------------------------

def choose_next_state(current_state, graph):

    transitions = graph["transitions"]
    regimes = graph.get("regimes", {})
    risk_targets = graph.get("risk_targets", [])

    possible = transitions.get(current_state, [])

    if not possible:
        return None

    # Avoid risk targets if possible
    safe = [s for s in possible if s not in risk_targets]

    if safe:
        return safe[0]

    return possible[0]


# -----------------------------------------------------------
# Navigation Loop
# -----------------------------------------------------------

def navigate_system(adapter, max_steps=20):

    graph = adapter.to_state_graph()

    states = graph["states"]
    transitions = graph["transitions"]
    regimes = graph.get("regimes", {})
    risk_targets = graph.get("risk_targets", [])

    current = graph.get("initial_state")

    if current is None:
        current = states[0]

    print("\n==============================")
    print("SYSTEM:", adapter.metadata().get("system", "Unknown"))
    print("==============================")

    print("\nStart State:", current)

    path = [current]

    for step in range(max_steps):

        next_state = choose_next_state(current, graph)

        if next_state is None:
            print("No further transitions.")
            break

        print(
            f"Step {step+1}:",
            current,
            "→",
            next_state,
            "| regime:", regimes.get(next_state)
        )

        path.append(next_state)

        if next_state in risk_targets:
            print("⚠ Risk state reached:", next_state)
            break

        current = next_state

    print("\nNavigation Path:")
    print(" → ".join(path))


# -----------------------------------------------------------
# Main Runner
# -----------------------------------------------------------

def main():

    adapters = [
        LorenzAdapter(),
        KuramotoAdapter(),
        PowerGridAdapter(),
        SupplyChainAdapter(),
        TrafficAdapter(),
    ]

    for adapter in adapters:
        navigate_system(adapter)


if __name__ == "__main__":
    main()
