"""Typed contracts for the NEXAH Orientation Layer."""

from .brief import (
    BriefEvidenceClass,
    BriefEvidenceStatement,
    BriefOutcomeStatus,
    BriefPerspective,
    BriefReproduction,
    OrientationBrief,
    generate_orientation_brief,
    render_orientation_brief_markdown,
)

from .evidence import (
    Evidence,
    EvidenceKind,
    Provenance,
    Uncertainty,
    UncertaintyKind,
)
from .generator import (
    OrientationReportGenerator,
    ReportGenerationError,
    generate_orientation_report,
)
from .memory import (
    Episode,
    EpisodeStore,
    EpisodeStoreError,
    JsonlEpisodeStore,
    attach_similar_episodes,
    orientation_similarity,
)
from .primitives import (
    Constraint,
    Context,
    EpisodeRef,
    Goal,
    MapRef,
    MapScope,
    Observation,
    Observer,
    OperatorRef,
    Option,
    OptionStatus,
    Outcome,
    ReferenceFrame,
    Regime,
    RepresentationRef,
    ScopedIdentifier,
    Similarity,
    StateRef,
    TimePoint,
    Transition,
)
from .report import OrientationReport
from .probes import (
    FindingStance,
    ProbeAgreement,
    ProbeContradiction,
    ProbeFinding,
    ProbeResult,
    ProbeSynthesis,
    synthesize_probe_results,
)
from .state import OrientationState

__all__ = [
    "BriefEvidenceClass",
    "BriefEvidenceStatement",
    "BriefOutcomeStatus",
    "BriefPerspective",
    "BriefReproduction",
    "Constraint",
    "Context",
    "EpisodeRef",
    "Episode",
    "EpisodeStore",
    "EpisodeStoreError",
    "Evidence",
    "EvidenceKind",
    "Goal",
    "MapRef",
    "MapScope",
    "JsonlEpisodeStore",
    "Observation",
    "Observer",
    "OperatorRef",
    "Option",
    "OptionStatus",
    "OrientationReport",
    "OrientationReportGenerator",
    "OrientationBrief",
    "OrientationState",
    "FindingStance",
    "ProbeAgreement",
    "ProbeContradiction",
    "ProbeFinding",
    "ProbeResult",
    "ProbeSynthesis",
    "Outcome",
    "Provenance",
    "ReferenceFrame",
    "ReportGenerationError",
    "Regime",
    "RepresentationRef",
    "ScopedIdentifier",
    "Similarity",
    "StateRef",
    "TimePoint",
    "Transition",
    "Uncertainty",
    "UncertaintyKind",
    "generate_orientation_report",
    "generate_orientation_brief",
    "attach_similar_episodes",
    "orientation_similarity",
    "synthesize_probe_results",
    "render_orientation_brief_markdown",
]
