"""
Pentagon Resonance Flow Demo
============================

This demo visualizes the vector flow generated by multiple attractors.

Instead of a scalar resonance field, we compute the gradient field
pointing toward the combined attractor potential.

This creates a flow map showing how trajectories move across the
landscape.

Kernel idea:

    F(x,y) = -∇R(x,y)

Where R(x,y) is the resonance potential.
"""

import math
import numpy as np
import matplotlib.pyplot as plt


# --------------------------------------------------
# Attractors
# --------------------------------------------------

attractors = {
    "Q1°": (-4, 0),
    "Q2°": (4, 0),
    "Q3°": (0, 4)
}


print("\nAttractors\n")
for name,pos in attractors.items():
    print(name,pos)


# --------------------------------------------------
# Grid
# --------------------------------------------------

xmin,xmax = -6,6
ymin,ymax = -6,6

resolution = 60

xs = np.linspace(xmin,xmax,resolution)
ys = np.linspace(ymin,ymax,resolution)

X,Y = np.meshgrid(xs,ys)

U = np.zeros_like(X)
V = np.zeros_like(Y)


# --------------------------------------------------
# Flow field
# --------------------------------------------------

epsilon = 0.3

for name,(ax,ay) in attractors.items():

    dx = X - ax
    dy = Y - ay

    dist = np.sqrt(dx*dx + dy*dy) + epsilon

    U += -dx / dist**3
    V += -dy / dist**3


# --------------------------------------------------
# Plot
# --------------------------------------------------

plt.figure(figsize=(7,6))

plt.streamplot(
    X,Y,U,V,
    density=1.4,
    linewidth=1
)

for name,(ax,ay) in attractors.items():

    plt.scatter(ax,ay,marker="*",s=250)
    plt.text(ax+0.2,ay+0.2,name)


plt.title("NEXAH Resonance Flow Field")
plt.xlabel("x")
plt.ylabel("y")

plt.xlim(xmin,xmax)
plt.ylim(ymin,ymax)

plt.gca().set_aspect("equal")

plt.tight_layout()
plt.show()
