"""
Pentagon Spiral Flow Field Demo
===============================

This demo visualizes a spiral flow field generated by multiple attractors.

The vector field combines two components:

1. Attraction toward attractors
2. Rotational spiral motion

Kernel idea:

    F(x,y) = -∇R(x,y) + ω * rotation(x,y)

This produces trajectories that spiral toward attractors instead
of moving in straight lines.

This demo extends the previous flow-field visualization by adding
a rotational component to the dynamics.
"""

import numpy as np
import matplotlib.pyplot as plt


# --------------------------------------------------
# Attractors
# --------------------------------------------------

attractors = {
    "Q1°": (-4, 0),
    "Q2°": (4, 0),
    "Q3°": (0, 4)
}

print("\nAttractors\n")
for name, pos in attractors.items():
    print(name, pos)


# --------------------------------------------------
# Grid
# --------------------------------------------------

xmin, xmax = -6, 6
ymin, ymax = -6, 6

resolution = 70

xs = np.linspace(xmin, xmax, resolution)
ys = np.linspace(ymin, ymax, resolution)

X, Y = np.meshgrid(xs, ys)

U = np.zeros_like(X)
V = np.zeros_like(Y)


# --------------------------------------------------
# Parameters
# --------------------------------------------------

epsilon = 0.4
rotation_strength = 0.9


# --------------------------------------------------
# Flow field computation
# --------------------------------------------------

for ax, ay in attractors.values():

    dx = X - ax
    dy = Y - ay

    dist = np.sqrt(dx*dx + dy*dy) + epsilon

    # attraction component
    U += -dx / dist**2
    V += -dy / dist**2

    # spiral rotation component
    U += -rotation_strength * dy / dist**2
    V +=  rotation_strength * dx / dist**2


# --------------------------------------------------
# Visualization
# --------------------------------------------------

plt.figure(figsize=(7,6))

plt.streamplot(
    X, Y,
    U, V,
    density=1.6,
    linewidth=1.1
)

for name, (ax, ay) in attractors.items():

    plt.scatter(ax, ay, marker="*", s=260)
    plt.text(ax+0.2, ay+0.2, name)

plt.title("NEXAH Pentagon Spiral Flow Field")
plt.xlabel("x")
plt.ylabel("y")

plt.xlim(xmin, xmax)
plt.ylim(ymin, ymax)

plt.gca().set_aspect("equal")

plt.tight_layout()
plt.show()
