"""
Pentagon Resonance Field Demo
=============================

This demo visualizes the resonance landscape generated by
multiple attractors in the NEXAH kernel.

Instead of computing basin membership, we compute a continuous
field representing the combined influence of the attractors.

Kernel idea:

    R(x,y) = Σ_i 1 / (distance_i + ε)

This produces a resonance intensity field across space.

Regions where attractor influences overlap create interference
patterns.

This illustrates the concept of a "resonance field" used in
Codex-style spatial analysis.
"""

import math
import numpy as np
import matplotlib.pyplot as plt


# --------------------------------------------------
# Attractors
# --------------------------------------------------

attractors = {
    "Q1°": (-4, 0),
    "Q2°": (4, 0),
    "Q3°": (0, 4)
}


print("\nAttractors\n")
for name,pos in attractors.items():
    print(name,pos)


# --------------------------------------------------
# Grid parameters
# --------------------------------------------------

xmin,xmax = -6,6
ymin,ymax = -6,6
resolution = 200

xs = np.linspace(xmin,xmax,resolution)
ys = np.linspace(ymin,ymax,resolution)

field = np.zeros((resolution,resolution))


# --------------------------------------------------
# Resonance field computation
# --------------------------------------------------

epsilon = 0.2

for iy,y in enumerate(ys):
    for ix,x in enumerate(xs):

        value = 0.0

        for ax,ay in attractors.values():

            dx = x-ax
            dy = y-ay

            dist = math.sqrt(dx*dx+dy*dy)

            value += 1/(dist+epsilon)

        field[iy,ix] = value


# --------------------------------------------------
# Visualization
# --------------------------------------------------

plt.figure(figsize=(7,6))

plt.imshow(
    field,
    origin="lower",
    extent=[xmin,xmax,ymin,ymax],
    cmap="plasma"
)

plt.colorbar(label="resonance intensity")

for name,(ax,ay) in attractors.items():

    plt.scatter(ax,ay,marker="*",s=250,color="white")
    plt.text(ax+0.2,ay+0.2,name,color="white")


plt.title("NEXAH Multi-Attractor Resonance Field")
plt.xlabel("x")
plt.ylabel("y")

plt.tight_layout()
plt.show()
