"""
Pentagon Spiral Particle Simulation Demo
========================================

This demo simulates particles moving through the spiral flow field
generated by multiple attractors.

Particles follow the vector field:

    dx/dt = F(x,y)

where

    F(x,y) = attraction + spiral rotation

The simulation visualizes how particles spiral toward attractors
over time.
"""

import numpy as np
import matplotlib.pyplot as plt


# --------------------------------------------------
# Attractors
# --------------------------------------------------

attractors = {
    "Q1°": (-4, 0),
    "Q2°": (4, 0),
    "Q3°": (0, 4)
}

print("\nAttractors\n")
for name,pos in attractors.items():
    print(name,pos)


# --------------------------------------------------
# Parameters
# --------------------------------------------------

epsilon = 0.4
rotation_strength = 0.9

particles = 400
steps = 180
dt = 0.08


# --------------------------------------------------
# Initial particle positions
# --------------------------------------------------

xmin, xmax = -6, 6
ymin, ymax = -6, 6

x = np.random.uniform(xmin, xmax, particles)
y = np.random.uniform(ymin, ymax, particles)

paths_x = [x.copy()]
paths_y = [y.copy()]


# --------------------------------------------------
# Vector field
# --------------------------------------------------

def flow_field(x, y):

    U = np.zeros_like(x)
    V = np.zeros_like(y)

    for ax, ay in attractors.values():

        dx = x - ax
        dy = y - ay

        dist = np.sqrt(dx*dx + dy*dy) + epsilon

        # attraction
        U += -dx / dist**2
        V += -dy / dist**2

        # spiral rotation
        U += -rotation_strength * dy / dist**2
        V +=  rotation_strength * dx / dist**2

    return U, V


# --------------------------------------------------
# Simulation loop
# --------------------------------------------------

for _ in range(steps):

    U, V = flow_field(x, y)

    x = x + U * dt
    y = y + V * dt

    paths_x.append(x.copy())
    paths_y.append(y.copy())


# --------------------------------------------------
# Visualization
# --------------------------------------------------

plt.figure(figsize=(7,6))

for i in range(particles):

    px = [p[i] for p in paths_x]
    py = [p[i] for p in paths_y]

    plt.plot(px, py, linewidth=0.5, alpha=0.5)


# draw attractors
for name,(ax,ay) in attractors.items():

    plt.scatter(ax,ay,marker="*",s=260)
    plt.text(ax+0.2,ay+0.2,name)


plt.title("NEXAH Spiral Particle Dynamics")
plt.xlabel("x")
plt.ylabel("y")

plt.xlim(xmin, xmax)
plt.ylim(ymin, ymax)

plt.gca().set_aspect("equal")

plt.tight_layout()
plt.show()
