"""
NEXAH Navigator

Core navigation engine for regime-aware system exploration.

The navigator operates on state graphs generated by adapters.

Pipeline:

State Graph
     ↓
Regime Scoring
     ↓
Risk Distance
     ↓
Lookahead Evaluation
     ↓
Navigation Policy
"""

from collections import deque


# -----------------------------------------------------------
# Regime scoring
# -----------------------------------------------------------

REGIME_STABILITY_SCORE = {
    "STABLE": 4.0,
    "COHERENT": 3.5,
    "LEFT_ATTRACTOR": 3.5,
    "RIGHT_ATTRACTOR": 3.5,
    "TRANSITION": 2.0,
    "STRESS": 1.5,
    "UNSTABLE": 1.0,
    "CRITICAL": 0.5,
    "FAILURE": -2.0,
    "COLLAPSE": -3.0,
    "ESCAPE": -3.0,
    "CHAOTIC_FLOW": 1.5,
}


def regime_score(state, graph):

    regimes = graph.get("regimes", {}) or {}
    label = regimes.get(state, "TRANSITION")

    return REGIME_STABILITY_SCORE.get(label, 1.0)


# -----------------------------------------------------------
# Risk distance
# -----------------------------------------------------------

def distance_to_nearest_risk(state, graph):

    transitions = graph.get("transitions", {}) or {}
    risk_targets = graph.get("risk_targets", []) or []

    if not risk_targets:
        return 999

    queue = deque([(state, 0)])
    visited = {state}

    while queue:

        node, dist = queue.popleft()

        if node in risk_targets:
            return dist

        for nxt in transitions.get(node, []):

            if nxt not in visited:

                visited.add(nxt)
                queue.append((nxt, dist + 1))

    return 999


# -----------------------------------------------------------
# Lookahead evaluation
# -----------------------------------------------------------

def evaluate_path(start_state, graph, depth=5):

    transitions = graph.get("transitions", {}) or {}
    risk_targets = set(graph.get("risk_targets", []) or [])

    total_score = 0
    current = start_state

    for step in range(depth):

        possible = transitions.get(current, [])

        if not possible:
            break

        scored = []

        for candidate in possible:

            stability = regime_score(candidate, graph)
            risk_distance = distance_to_nearest_risk(candidate, graph)
            is_risk = 1 if candidate in risk_targets else 0

            score = (
                stability * 10.0
                + risk_distance * 2.0
                - is_risk * 100.0
            )

            scored.append((score, candidate))

        scored.sort(reverse=True)

        best_score, best_state = scored[0]

        total_score += best_score * (0.9 ** step)

        if best_state in risk_targets:
            break

        current = best_state

    return total_score


# -----------------------------------------------------------
# Navigation policy
# -----------------------------------------------------------

def choose_next_state(current_state, graph):

    transitions = graph.get("transitions", {}) or {}

    possible = transitions.get(current_state, [])

    if not possible:
        return None

    scored = []

    for candidate in possible:

        score = evaluate_path(candidate, graph)

        scored.append((score, candidate))

    scored.sort(reverse=True)

    return scored[0][1]


# -----------------------------------------------------------
# Navigator class
# -----------------------------------------------------------

class NexahNavigator:

    def __init__(self, adapter):

        self.adapter = adapter
        self.graph = adapter.to_state_graph()

    def navigate(self, max_steps=20):

        states = self.graph.get("states", [])
        regimes = self.graph.get("regimes", {}) or {}
        risk_targets = self.graph.get("risk_targets", []) or []

        current = self.graph.get("initial_state")

        if current is None and states:
            current = states[0]

        path = [current]

        visited_count = {current: 1}

        for step in range(max_steps):

            next_state = choose_next_state(current, self.graph)

            if next_state is None:
                break

            path.append(next_state)

            if next_state in risk_targets:
                break

            visited_count[next_state] = visited_count.get(next_state, 0) + 1

            if visited_count[next_state] > 5:
                break

            current = next_state

        return path
