"""
Pentagon Ring Spiral Particle Demo
=================================

Particles move inside a spiral flow field generated by
five attractors arranged on a pentagon.

The flow field combines:

    attraction + rotation

Particles spiral toward the nearest attractor while
the pentagon symmetry produces complex resonance patterns.
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation


# --------------------------------------------------
# Generate pentagon attractors
# --------------------------------------------------

radius = 4.5
num_attractors = 5

attractors = {}

for i in range(num_attractors):

    angle = 2*np.pi*i/num_attractors + np.pi/2

    x = radius*np.cos(angle)
    y = radius*np.sin(angle)

    attractors[f"Q{i+1}°"] = (x,y)


print("\nAttractors\n")
for name,pos in attractors.items():
    print(name,pos)


# --------------------------------------------------
# Parameters
# --------------------------------------------------

epsilon = 0.45
rotation_strength = 0.95

particles = 600
dt = 0.07

xmin,xmax = -7,7
ymin,ymax = -7,7


# --------------------------------------------------
# Initial particle positions
# --------------------------------------------------

x = np.random.uniform(xmin,xmax,particles)
y = np.random.uniform(ymin,ymax,particles)


# --------------------------------------------------
# Flow field
# --------------------------------------------------

def flow_field(x,y):

    U = np.zeros_like(x)
    V = np.zeros_like(y)

    for ax,ay in attractors.values():

        dx = x-ax
        dy = y-ay

        dist = np.sqrt(dx*dx+dy*dy) + epsilon

        # attraction
        U += -dx/dist**2
        V += -dy/dist**2

        # spiral rotation
        U += -rotation_strength*dy/dist**2
        V +=  rotation_strength*dx/dist**2

    return U,V


# --------------------------------------------------
# Plot
# --------------------------------------------------

fig,ax = plt.subplots(figsize=(7,7))

scatter = ax.scatter(x,y,s=8)

for name,(axp,ayp) in attractors.items():

    ax.scatter(axp,ayp,marker="*",s=260)
    ax.text(axp+0.2,ayp+0.2,name)


ax.set_xlim(xmin,xmax)
ax.set_ylim(ymin,ymax)

ax.set_aspect("equal")

ax.set_title("NEXAH Pentagon Ring Spiral Dynamics")


# --------------------------------------------------
# Animation step
# --------------------------------------------------

def update(frame):

    global x,y

    U,V = flow_field(x,y)

    x = x + U*dt
    y = y + V*dt

    scatter.set_offsets(np.c_[x,y])

    return scatter,


ani = FuncAnimation(
    fig,
    update,
    frames=350,
    interval=40,
    blit=True
)

plt.show()
