"""
NEXAH Risk-Aware Navigation Demo

This script demonstrates how the NEXAH framework can navigate
state graphs generated by external system adapters.

Pipeline:

External System
      ↓
Adapter
      ↓
State Graph
      ↓
Regime Scoring
      ↓
Risk-Aware Navigation Policy
      ↓
Path through the system

Goal:
Prefer stable regimes, avoid risk targets, and maximize distance
from collapse or failure states where possible.
"""

from collections import deque

from APPLICATIONS.adapters.examples.lorenz_adapter import LorenzAdapter
from APPLICATIONS.adapters.examples.kuramoto_adapter import KuramotoAdapter
from APPLICATIONS.adapters.examples.powergrid_adapter import PowerGridAdapter
from APPLICATIONS.adapters.examples.supply_chain_adapter import SupplyChainAdapter
from APPLICATIONS.adapters.examples.traffic_adapter import TrafficAdapter


# -----------------------------------------------------------
# Regime scoring
# -----------------------------------------------------------

REGIME_STABILITY_SCORE = {
    "STABLE": 4.0,
    "COHERENT": 3.5,
    "LEFT_ATTRACTOR": 3.5,
    "RIGHT_ATTRACTOR": 3.5,
    "TRANSITION": 2.0,
    "STRESS": 1.5,
    "UNSTABLE": 1.0,
    "CRITICAL": 0.5,
    "FAILURE": -2.0,
    "COLLAPSE": -3.0,
    "ESCAPE": -3.0,
    "CHAOTIC_FLOW": 1.5,
}


def regime_score(state, graph):
    regimes = graph.get("regimes", {}) or {}
    label = regimes.get(state, "TRANSITION")
    return REGIME_STABILITY_SCORE.get(label, 1.0)


# -----------------------------------------------------------
# Graph utilities
# -----------------------------------------------------------

def build_reverse_graph(transitions):
    reverse = {}
    for src, targets in transitions.items():
        for dst in targets:
            reverse.setdefault(dst, []).append(src)
    return reverse


def distance_to_nearest_risk(state, graph):
    """
    Compute shortest path distance from `state` to the nearest risk target.
    If no path exists, return a large value.
    If there are no risk targets, also return a large value.
    """
    transitions = graph.get("transitions", {}) or {}
    risk_targets = graph.get("risk_targets", []) or []

    if not risk_targets:
        return 999

    # BFS from current state to nearest risk target
    queue = deque([(state, 0)])
    visited = {state}

    while queue:
        node, dist = queue.popleft()

        if node in risk_targets:
            return dist

        for nxt in transitions.get(node, []):
            if nxt not in visited:
                visited.add(nxt)
                queue.append((nxt, dist + 1))

    return 999


# -----------------------------------------------------------
# Navigation policy
# -----------------------------------------------------------

def choose_next_state(current_state, graph):
    """
    Risk-aware policy:
    - avoid risk targets when possible
    - prefer stable regimes
    - prefer states farther away from risk targets
    """
    transitions = graph.get("transitions", {}) or {}
    risk_targets = set(graph.get("risk_targets", []) or [])

    possible = transitions.get(current_state, [])

    if not possible:
        return None

    scored_candidates = []

    for candidate in possible:
        is_risk = 1 if candidate in risk_targets else 0
        stability = regime_score(candidate, graph)
        risk_distance = distance_to_nearest_risk(candidate, graph)

        # Higher is better
        score = (
            stability * 10.0
            + risk_distance * 2.0
            - is_risk * 100.0
        )

        scored_candidates.append(
            (
                score,
                candidate,
                stability,
                risk_distance,
                is_risk,
            )
        )

    scored_candidates.sort(key=lambda x: x[0], reverse=True)
    best = scored_candidates[0]

    return best[1]


# -----------------------------------------------------------
# Navigation loop
# -----------------------------------------------------------

def navigate_system(adapter, max_steps=20):
    graph = adapter.to_state_graph()

    states = graph.get("states", [])
    regimes = graph.get("regimes", {}) or {}
    risk_targets = graph.get("risk_targets", []) or []

    current = graph.get("initial_state")
    if current is None and states:
        current = states[0]

    print("\n==============================")
    print("SYSTEM:", adapter.metadata().get("system", "Unknown"))
    print("==============================")

    if current is None:
        print("\nNo initial state available.")
        return

    print("\nStart State:", current)
    print("Start Regime:", regimes.get(current, "UNKNOWN"))

    path = [current]
    visited_count = {current: 1}

    for step in range(max_steps):
        next_state = choose_next_state(current, graph)

        if next_state is None:
            print("No further transitions.")
            break

        next_regime = regimes.get(next_state, "UNKNOWN")
        next_distance = distance_to_nearest_risk(next_state, graph)
        next_stability = regime_score(next_state, graph)

        print(
            f"Step {step + 1}: "
            f"{current} → {next_state} "
            f"| regime: {next_regime} "
            f"| stability_score: {next_stability:.1f} "
            f"| distance_to_risk: {next_distance}"
        )

        path.append(next_state)

        if next_state in risk_targets:
            print("⚠ Risk state reached:", next_state)
            break

        visited_count[next_state] = visited_count.get(next_state, 0) + 1

        # Simple loop guard: if we are cycling too much, stop
        if visited_count[next_state] > 5:
            print("Loop detected: stopping navigation.")
            break

        current = next_state

    print("\nNavigation Path:")
    print(" → ".join(path))

    if risk_targets:
        print("\nRisk Targets:", ", ".join(risk_targets))


# -----------------------------------------------------------
# Main runner
# -----------------------------------------------------------

def main():
    adapters = [
        LorenzAdapter(),
        KuramotoAdapter(),
        PowerGridAdapter(),
        SupplyChainAdapter(),
        TrafficAdapter(),
    ]

    for adapter in adapters:
        navigate_system(adapter)


if __name__ == "__main__":
    main()
